# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import virtuo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=35)),
                ('course_id', models.CharField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=35)),
                ('material_link', models.FileField(blank=True, null=True, upload_to=virtuo.models.user_directory_path)),
                ('uploaded_by', models.CharField(blank=True, max_length=35, null=True)),
                ('m_type', models.CharField(choices=[('PPT', 'Presentation'), ('VID', 'Video')], max_length=3, null=True)),
                ('material_upload', models.FileField(upload_to=b'')),
                ('related_course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='virtuo.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, null=True)),
                ('asked_by', models.CharField(max_length=10)),
                ('answered_by', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField()),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtuo.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enrollment_no', models.CharField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('courses', models.ManyToManyField(to='virtuo.Course')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=35, primary_key=True, serialize=False, unique=True)),
                ('courses', models.ManyToManyField(to='virtuo.Course')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
